import './globals.css';

import type { Metadata } from 'next';
import pretendard from '@/fonts/font';
import KakaoScript from '@/components/KakaoScript';
import QueryProvider from '@/QueryProvider';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${pretendard.className}`}>
        <KakaoScript />
        {/* eslint-disable-next-line @next/next/no-before-interactive-script-outside-document */}
        <Script
          strategy="beforeInteractive"
          id="naver-map-script"
          type="text/javascript"
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env
            .NEXT_PUBLIC_NMAP_KEY!}&submodules=geocoder`}
        />
        <QueryProvider>
          <div className="flex justify-center items-center">
            <main className="w-sm md:w-md min-h-screen flex flex-col relative">
              <section className="overflow-y-auto pb-[3.625rem] pt-14">{children}</section>
            </main>
          </div>
          <div id="modal"></div>
        </QueryProvider>
      </body>
    </html>
  );
}
